FROM mambaorg/micromamba AS pycairo
USER root
RUN apt-get update && apt-get install -y procps python3-pip cmake r-base libcurl4-openssl-dev r-cran-lme4
COPY --chown=$MAMBA_USER:$MAMBA_USER envs/*.yaml /
RUN micromamba install -y -n base --file /pycairo.yaml && \
        micromamba clean --all --yes
